[build]
  # Build command - change to client dir and build
  command = "cd client && npm install --legacy-peer-deps && npm run build"
  
  # Publish directory - absolute path from repo root
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# API proxy to your Railway backend (must come first!)
[[redirects]]
  from = "/api/*"
  to = "https://web-production-e1fae.up.railway.app/api/:splat"
  status = 200
  force = true

# Redirect all OTHER routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200