[build]
  # Build command - since we're already in client dir  
  command = "npm install --legacy-peer-deps && npm run build"
  
  # Publish directory - relative to current dir
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy to your Railway backend
[[redirects]]
  from = "/api/*"
  to = "https://choreworld-production.up.railway.app/api/:splat"
  status = 200
  force = true