[build]
  # Directory to build from
  base = "client"
  
  # Build command
  command = "npm run build"
  
  # Directory to publish (relative to base)
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy will be configured after backend deployment
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-url.onrender.com/api/:splat"
#   status = 200
#   force = true