[build]
  # Build command - change to client dir and build
  command = "cd client && npm install && npm run build"
  
  # Publish directory - absolute path from repo root
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy to your Render backend
[[redirects]]
  from = "/api/*"
  to = "https://choreworld.onrender.com/api/:splat"
  status = 200
  force = true